import { MAX_PARTICIPANTES, MAX_TRANSMISSORES } from "./limits.js";
import type {
  AppToSignalerMessage,
  EntryRefusedReason,
  ParticipanteLeftReason,
  SignalerToAppMessage,
} from "./messages.js";
import { PROTOCOL_VERSION } from "./version.js";

export type ParticipanteState = "pending-approval" | "admitted" | "left";

export interface InternalParticipante {
  id: string;
  name: string;
  state: ParticipanteState;
  /**
   * A chave do pedido de entrada que criou este Participante (`joinNonce` em `messages.ts`).
   * Mesma chave == mesmo app pedindo de novo, e o pedido novo substitui o antigo.
   */
  joinNonce: string;
}

export interface SessaoState {
  readonly codigoDeSessao: string;
  readonly protocolVersion: number;
  readonly anfitriaoId: string;
  readonly participantes: ReadonlyMap<string, InternalParticipante>;
  readonly transmissores: readonly string[];
  readonly ended: boolean;
}

/** Describes a message to send; does not send it. Whoever executes the effects decides delivery. */
export interface Effect {
  readonly toParticipanteIds: readonly string[];
  readonly message: SignalerToAppMessage;
}

export interface TransitionResult {
  readonly state: SessaoState;
  readonly effects: readonly Effect[];
}

function admittedParticipantes(state: {
  participantes: ReadonlyMap<string, InternalParticipante>;
}): InternalParticipante[] {
  return [...state.participantes.values()].filter((p) => p.state === "admitted");
}

function admittedIds(state: { participantes: ReadonlyMap<string, InternalParticipante> }): string[] {
  return admittedParticipantes(state).map((p) => p.id);
}

function withoutParticipanteId(ids: readonly string[], excluded: string): string[] {
  return ids.filter((id) => id !== excluded);
}

function withParticipantes(
  state: SessaoState,
  participantes: ReadonlyMap<string, InternalParticipante>,
): SessaoState {
  return { ...state, participantes };
}

// ---------------------------------------------------------------------------
// Sessao creation
// ---------------------------------------------------------------------------

export interface CreateSessaoInput {
  readonly participanteId: string;
  readonly name: string;
  readonly protocolVersion: number;
  readonly joinNonce: string;
  /** Injectable for deterministic tests; normally generated by `generateCodigoDeSessao`. */
  readonly codigoDeSessao: string;
}

export type CreateSessaoResult =
  | { readonly state: SessaoState; readonly effects: readonly Effect[] }
  | { readonly state: null; readonly effects: readonly Effect[] };

export function createSessao(input: CreateSessaoInput): CreateSessaoResult {
  if (input.protocolVersion !== PROTOCOL_VERSION) {
    return {
      state: null,
      effects: [
        {
          toParticipanteIds: [input.participanteId],
          message: { type: "entry-refused", reason: "incompatible-version" },
        },
      ],
    };
  }

  const anfitriao: InternalParticipante = {
    id: input.participanteId,
    name: input.name,
    state: "admitted",
    joinNonce: input.joinNonce,
  };

  const state: SessaoState = {
    codigoDeSessao: input.codigoDeSessao,
    protocolVersion: PROTOCOL_VERSION,
    anfitriaoId: input.participanteId,
    participantes: new Map([[anfitriao.id, anfitriao]]),
    transmissores: [],
    ended: false,
  };

  return {
    state,
    effects: [
      {
        toParticipanteIds: [input.participanteId],
        message: {
          type: "sessao-created",
          codigoDeSessao: input.codigoDeSessao,
          participanteId: input.participanteId,
        },
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// Transitions
// ---------------------------------------------------------------------------

/**
 * `senderId` is the `participanteId` assigned by the signaler on connection for whoever sent
 * `message` — including for `join`, where the sender is not yet in the roster.
 */
export function processMessage(
  state: SessaoState,
  senderId: string,
  message: AppToSignalerMessage,
): TransitionResult {
  switch (message.type) {
    case "join":
      return processJoin(state, senderId, message);
    case "respond-entry":
      return processRespondEntry(state, senderId, message);
    case "expel":
      return processExpel(state, senderId, message);
    case "request-palco":
      return processRequestPalco(state, senderId);
    case "release-palco":
      return processReleasePalco(state, senderId);
    case "signal":
      return processSignal(state, senderId, message);
    case "leave":
      return processLeave(state, senderId);
    case "create-sessao":
      // Only meaningful before the Sessao exists; discarded on an already-created Sessao.
      return noEffect(state);
  }
}

function noEffect(state: SessaoState): TransitionResult {
  return { state, effects: [] };
}

function refuseEntry(
  state: SessaoState,
  senderId: string,
  reason: EntryRefusedReason,
): TransitionResult {
  return {
    state,
    effects: [
      {
        toParticipanteIds: [senderId],
        message: { type: "entry-refused", reason },
      },
    ],
  };
}

function processJoin(
  state: SessaoState,
  senderId: string,
  message: Extract<AppToSignalerMessage, { type: "join" }>,
): TransitionResult {
  if (message.protocolVersion !== state.protocolVersion) {
    return refuseEntry(state, senderId, "incompatible-version");
  }
  if (message.codigoDeSessao !== state.codigoDeSessao) {
    return refuseEntry(state, senderId, "invalid-code");
  }

  // O mesmo app pedindo de novo substitui o próprio pedido anterior; sem isto, uma conexão que
  // morreu sem `close` (queda meio-aberta, hibernação) continua ocupando vaga e vira uma segunda
  // linha no roster com o mesmo humano atrás. Só depois disto a Sessão é medida como cheia — o
  // fantasma não pode roubar a vaga de quem ele mesmo é.
  const participantes = new Map(state.participantes);
  const superseded = [...participantes.values()].filter(
    (p) => p.joinNonce === message.joinNonce && p.id !== senderId,
  );
  const effects: Effect[] = [];
  for (const ghost of superseded) {
    participantes.delete(ghost.id);
    effects.push(
      ghost.state === "pending-approval"
        ? {
            toParticipanteIds: [state.anfitriaoId],
            message: { type: "entry-request-withdrawn", participanteId: ghost.id },
          }
        : {
            toParticipanteIds: withoutParticipanteId(admittedIds({ participantes }), ghost.id),
            message: { type: "participante-left", participanteId: ghost.id, reason: "disconnected" },
          },
    );
  }
  const transmissores = state.transmissores.filter((id) => participantes.has(id));
  if (transmissores.length !== state.transmissores.length) {
    effects.push({
      toParticipanteIds: admittedIds({ participantes }),
      message: { type: "transmissores-changed", participanteIds: [...transmissores] },
    });
  }

  if (participantes.size >= MAX_PARTICIPANTES) {
    // Os fantasmas já saíram acima; a recusa vale, mas os efeitos da limpeza ainda precisam sair.
    return {
      state: { ...state, participantes, transmissores },
      effects: [...effects, { toParticipanteIds: [senderId], message: { type: "entry-refused", reason: "sessao-full" } }],
    };
  }

  participantes.set(senderId, {
    id: senderId,
    name: message.name,
    state: "pending-approval",
    joinNonce: message.joinNonce,
  });

  return {
    state: { ...state, participantes, transmissores },
    effects: [
      ...effects,
      {
        toParticipanteIds: [state.anfitriaoId],
        message: { type: "entry-request", participanteId: senderId, name: message.name },
      },
    ],
  };
}

function processRespondEntry(
  state: SessaoState,
  senderId: string,
  message: Extract<AppToSignalerMessage, { type: "respond-entry" }>,
): TransitionResult {
  if (senderId !== state.anfitriaoId) {
    return noEffect(state);
  }
  const target = state.participantes.get(message.participanteId);
  if (!target || target.state !== "pending-approval") {
    return noEffect(state);
  }

  const participantes = new Map(state.participantes);

  if (message.approved) {
    participantes.set(target.id, { ...target, state: "admitted" });
    const newState = withParticipantes(state, participantes);
    const roster = admittedParticipantes(newState).map((p) => ({ id: p.id, name: p.name }));

    return {
      state: newState,
      effects: [
        {
          toParticipanteIds: [target.id],
          message: {
            type: "entry-approved",
            participanteId: target.id,
            roster,
            transmissores: [...newState.transmissores],
          },
        },
        {
          toParticipanteIds: withoutParticipanteId(admittedIds(newState), target.id),
          message: { type: "participante-joined", participante: { id: target.id, name: target.name } },
        },
      ],
    };
  }

  participantes.delete(target.id);
  return {
    state: withParticipantes(state, participantes),
    effects: [
      {
        toParticipanteIds: [target.id],
        message: { type: "entry-refused", reason: "refused-by-anfitriao" },
      },
    ],
  };
}

function processExpel(
  state: SessaoState,
  senderId: string,
  message: Extract<AppToSignalerMessage, { type: "expel" }>,
): TransitionResult {
  if (senderId !== state.anfitriaoId) {
    return noEffect(state);
  }
  const targetId = message.participanteId;
  if (targetId === state.anfitriaoId) {
    return noEffect(state);
  }
  const target = state.participantes.get(targetId);
  if (!target) {
    return noEffect(state);
  }

  const participantes = new Map(state.participantes);
  participantes.delete(targetId);
  const wasTransmissor = state.transmissores.includes(targetId);
  const transmissores = wasTransmissor
    ? withoutParticipanteId(state.transmissores, targetId)
    : state.transmissores;
  const newState: SessaoState = { ...state, participantes, transmissores };

  const effects: Effect[] = [
    {
      toParticipanteIds: admittedIds(newState),
      message: { type: "participante-left", participanteId: targetId, reason: "expelled" },
    },
  ];
  if (wasTransmissor) {
    effects.push({
      toParticipanteIds: admittedIds(newState),
      message: { type: "transmissores-changed", participanteIds: [...transmissores] },
    });
  }

  return { state: newState, effects };
}

function processRequestPalco(state: SessaoState, senderId: string): TransitionResult {
  const sender = state.participantes.get(senderId);
  if (!sender || sender.state !== "admitted") {
    return noEffect(state);
  }
  if (state.transmissores.includes(senderId)) {
    return noEffect(state);
  }

  if (state.transmissores.length >= MAX_TRANSMISSORES) {
    return {
      state,
      effects: [
        {
          toParticipanteIds: [senderId],
          message: { type: "palco-denied", reason: "palco-full" },
        },
      ],
    };
  }

  const transmissores = [...state.transmissores, senderId];
  const newState: SessaoState = { ...state, transmissores };
  return {
    state: newState,
    effects: [
      {
        toParticipanteIds: admittedIds(newState),
        message: { type: "transmissores-changed", participanteIds: transmissores },
      },
    ],
  };
}

function processReleasePalco(state: SessaoState, senderId: string): TransitionResult {
  if (!state.transmissores.includes(senderId)) {
    return noEffect(state);
  }
  const transmissores = withoutParticipanteId(state.transmissores, senderId);
  const newState: SessaoState = { ...state, transmissores };
  return {
    state: newState,
    effects: [
      {
        toParticipanteIds: admittedIds(newState),
        message: { type: "transmissores-changed", participanteIds: transmissores },
      },
    ],
  };
}

function processSignal(
  state: SessaoState,
  senderId: string,
  message: Extract<AppToSignalerMessage, { type: "signal" }>,
): TransitionResult {
  const sender = state.participantes.get(senderId);
  if (!sender || sender.state !== "admitted") {
    return noEffect(state);
  }
  const target = state.participantes.get(message.toParticipanteId);
  if (!target || target.state !== "admitted") {
    return noEffect(state);
  }

  return {
    state,
    effects: [
      {
        toParticipanteIds: [target.id],
        message: { type: "signal", fromParticipanteId: senderId, payload: message.payload },
      },
    ],
  };
}

/**
 * `reason` distinguishes an explicit `leave` message (the default, `'left'`) from the signaler
 * noticing a dropped connection (`'disconnected'`) — the anfitriao branch always reports
 * `'anfitriao-left'` regardless, since that is a property of who left, not how.
 */
export function processLeave(
  state: SessaoState,
  senderId: string,
  reason: Extract<ParticipanteLeftReason, "left" | "disconnected"> = "left",
): TransitionResult {
  const sender = state.participantes.get(senderId);
  if (!sender) {
    return noEffect(state);
  }

  if (sender.state === "pending-approval") {
    const participantes = new Map(state.participantes);
    participantes.delete(senderId);
    return {
      state: withParticipantes(state, participantes),
      effects: [
        {
          toParticipanteIds: [state.anfitriaoId],
          message: { type: "entry-request-withdrawn", participanteId: senderId },
        },
      ],
    };
  }

  if (senderId === state.anfitriaoId) {
    const participantes = new Map(state.participantes);
    participantes.delete(senderId);
    const newState: SessaoState = {
      ...state,
      participantes,
      transmissores: [],
      ended: true,
    };
    return {
      state: newState,
      effects: [
        {
          toParticipanteIds: admittedIds(newState),
          message: { type: "sessao-ended", reason: "anfitriao-left" },
        },
      ],
    };
  }

  const participantes = new Map(state.participantes);
  participantes.delete(senderId);
  const wasTransmissor = state.transmissores.includes(senderId);
  const transmissores = wasTransmissor
    ? withoutParticipanteId(state.transmissores, senderId)
    : state.transmissores;
  const newState: SessaoState = { ...state, participantes, transmissores };

  const effects: Effect[] = [
    {
      toParticipanteIds: admittedIds(newState),
      message: { type: "participante-left", participanteId: senderId, reason },
    },
  ];
  if (wasTransmissor) {
    effects.push({
      toParticipanteIds: admittedIds(newState),
      message: { type: "transmissores-changed", participanteIds: [...transmissores] },
    });
  }

  return { state: newState, effects };
}
